### ISSUE TITLE
ускорить сборку boost.asio

### ISSUE THREAD

**Issue by tritseratop** [bachmak/petworking#6]
и вынеси stdaxf(?) в корень

**Comment by bachmak** [comment]
мне кажется, что путь решения проблемы следующий:
- добавить через CMakeLists.txt (функция [add_compile_definitions](https://cmake.org/cmake/help/latest/command/add_compile_definitions.html)) всем таргетам, использующим stdafx.h, макрос BOOST_ASIO_SEPARATE_COMPILATION
- добавить отдельный таргет [STATIC](https://cmake.org/cmake/help/latest/command/add_library.html#id2) или [OBJECT](https://cmake.org/cmake/help/latest/command/add_library.html#id3) библиотек из одного .cpp-файла, подключающего boost/asio.hpp
- подключить таргет с asio в остальные таргеты
